### ISSUE TITLE
IDA7.0 mipsrop.py

### ISSUE THREAD

**Issue by ifelsethen** [devttys0/ida#27]
Traceback (most recent call last):
  File "D:/IDA 7.0/plugins/mipsrop.py", line 721, in activate
    mipsrop = MIPSROPFinder()
  File "D:/IDA 7.0/plugins/mipsrop.py", line 208, in __init__
    self._initial_find()
  File "D:/IDA 7.0/plugins/mipsrop.py", line 226, in _initial_find
    self.system_calls += self._find_system_calls(start, end)
  File "D:/IDA 7.0/plugins/mipsrop.py", line 393, in _find_system_calls
    if ea >= start_ea and ea <= end_ea and idc.GetMnem(ea)[0] in ['j', 'b']:
IndexError: string index out of range

**Comment by yxshyj** [comment]
Oh,maybe you should try delete code "and idc.GetMnem(ea)[0] in ['j', 'b']",resolve it~

**Comment by X1ngn** [comment]
I have the same problem. When I comment out the system call functions, it works. The gadget for the system call was not found, though.
