### ISSUE TITLE
 No such file or directory shims\__init__.py

### ISSUE THREAD

**Issue by yooo1999** [devttys0/ida#53]
I have tried to install plugin directory into IDA8.1 directory in Windows OS:

`python install.py  --install -d "c:\Program Files\IDA Pro 8.1"
`
But I got an error:
```

Installing plugins from c:\Users\xxxxx\Desktop\ida\plugins to c:\Program Files\IDA Pro 8.1\plugins...
Installing alleycat...alleycat is not a known plugin. Skipping copy...Done
Installing codatify...codatify is not a known plugin. Skipping copy...Done
Installing fluorescence...fluorescence is not a known plugin. Skipping copy...Done
Installing funcprofiler...funcprofiler is not a known plugin. Skipping copy...Done
Installing leafblower...leafblower is not a known plugin. Skipping copy...Done
Installing localxrefs...localxrefs is not a known plugin. Skipping copy...Done
Installing mipslocalvars...mipslocalvars is not a known plugin. Skipping copy...Done
Installing mipsrop...mipsrop is not a known plugin. Skipping copy...Done
Installing rizzo...rizzo is not a known plugin. Skipping copy...Done
Installing shims...Traceback (most recent call last):
  File "install.py", line 108, in <module>
    install_plugins(args.directory)
  File "install.py", line 50, in install_plugins
    open(os.path.join(shims_dir, '__init__.py'), 'a').close()
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Program Files\\IDA Pro 8.1\\plugins\\shims\\__init__.py'
```

https://github.com/tacnetsol/ida/blob/master/plugins/install.py#L50

**Comment by mzpqnxow** [comment]
I vaguely remember having this issue. Manually create that shims directory and run the script again

(add an os.mkdir into the script)

Or... just manually copy the files

**Comment by asfandiyar007** [comment]
I got the same kinda error that was saying **_couldn't find "from shims import ida_shims"._**
 I fixed it by making shims directory in "plugins" and then created ida_shims.py and pasted the code from [https://github.com/grayhatacademy/ida/blob/master/plugins/shims/ida_shims.py](url) and now the error is gone. Hope this helps
